### ISSUE TITLE
Weird icons/chars shown when rendering icons

### ISSUE THREAD

**Issue by Panthro** [phucgaoxam/line_awesome_icons_flutter#2]
All the icons from this screenshot are from the line_awesome_icons package, some users reported issues with font_awesome icons as well, but in that case only the rectangular X was being shown.

Here here are chinese/japanese/korean (sorry don't know much of it) chars that I have no idea where are coming from.

Might it be some charset related thing? UTF-8 vs UTF-16?

![screenshot_20190112-133227](https://user-images.githubusercontent.com/1565421/51075230-129b2980-1689-11e9-9058-7acc1f485146.jpg)

**Comment by phucgaoxam** [comment]
@Panthro can you please tell me which icon is that?

**Comment by Panthro** [comment]
The tab icons to give un an example

```
LineAwesomeIcons.clock_o
LineAwesomeIcons.pencil_square
LineAwesomeIcons.barcode
LineAwesomeIcons.dollar
```

**Comment by phucgaoxam** [comment]
@Panthro do you use any specific fonts in your application? Or at least any specific so I can reproduce this bug

**Comment by Panthro** [comment]
Yes

I have a font generated with http://fluttericon.com with some custom icons

(cannot attach it here for inspection, if you need the specific font let me know and I upload it somewhere)

**Comment by phucgaoxam** [comment]
Yeah please share me the font on Gitter (phucgaoxam)

**Comment by RichieMcMullen** [comment]
I'm still having this issue. All icons see to render as Chinese symbols.
